"use client";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowRight, Calendar, ChevronRight, Mail, Sprout, TentTree } from "lucide-react";
import { useState } from "react";
const items = [
  { icon: Mail, title: "3 important emails need replies", note: "Two arrived yesterday", color: "text-sky-300 bg-sky-400/10" },
  { icon: Sprout, title: "SAT practice has slowed this week", note: "Down 30% from last week", color: "text-amber-300 bg-amber-400/10" },
  { icon: TentTree, title: "Eagle Project has had no activity in 12 days", note: "Last update: July 3", color: "text-violet-300 bg-violet-400/10" },
  { icon: Calendar, title: "Volunteer shift this Sunday", note: "10:00 AM — Community Food Bank", color: "text-emerald-300 bg-emerald-400/10" }
];
export function BriefingCard() { const [expanded, setExpanded] = useState(false); const shown = expanded ? items : items.slice(0, 3); return <section className="overflow-hidden rounded-2xl border border-white/[.09] bg-gradient-to-br from-white/[.065] to-white/[.018] shadow-panel"><div className="flex items-start justify-between border-b border-white/[.07] p-5"><div><div className="mb-2 flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-violet-400 shadow-[0_0_10px_#a78bfa]" /><span className="text-xs font-medium uppercase tracking-[.15em] text-violet-200">Daily briefing</span></div><h2 className="text-lg font-medium tracking-tight">A few things need your attention.</h2></div><button className="grid h-8 w-8 place-items-center rounded-lg bg-white/[.06] text-zinc-400 hover:text-white"><ChevronRight size={16} /></button></div><div className="p-2">{shown.map((item, i) => { const Icon = item.icon; return <motion.button initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * .06 }} className="flex w-full items-center gap-3 rounded-xl p-3 text-left hover:bg-white/[.045]" key={item.title}><div className={`grid h-9 w-9 shrink-0 place-items-center rounded-lg ${item.color}`}><Icon size={17} /></div><div className="min-w-0 flex-1"><p className="truncate text-sm text-zinc-200">{item.title}</p><p className="mt-0.5 text-xs text-zinc-600">{item.note}</p></div><ArrowRight size={15} className="text-zinc-700" /></motion.button>; })}</div><AnimatePresence>{!expanded && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="border-t border-white/[.06] p-3"><button onClick={() => setExpanded(true)} className="w-full rounded-lg py-1.5 text-xs font-medium text-zinc-400 transition-colors hover:bg-white/[.05] hover:text-zinc-100">Show all insights</button></motion.div>}</AnimatePresence></section>; }
