"use client";
import { CalendarDays, CheckSquare, ChevronDown, Grid2X2, Inbox, PanelLeftClose, Puzzle, Settings, Sparkles, ShieldCheck, LogOut } from "lucide-react";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { motion } from "framer-motion";
import { DonnaMark } from "@/components/donna-mark";
import { cn } from "@/lib/utils";

const items = [{ label: "Dashboard", href: "/dashboard", icon: Grid2X2 }, { label: "Today", href: "/today", icon: Sparkles }, { label: "Calendar", href: "/calendar", icon: CalendarDays }, { label: "Tasks", href: "/tasks", icon: CheckSquare }, { label: "Messages", href: "/messages", icon: Inbox }];
export function Sidebar() { const path=usePathname(); const router=useRouter(); const signOut=()=>{localStorage.removeItem("donna-session");router.push("/login");}; const nav=(label:string,href:string,Icon:typeof Grid2X2)=><Link href={href} className={cn("flex h-10 items-center gap-3 rounded-lg px-3 text-sm transition-colors", path===href ? "bg-white/[.09] font-medium text-white" : "text-zinc-500 hover:bg-white/[.05] hover:text-zinc-200")}><Icon size={17} strokeWidth={1.8}/>{label}</Link>; return <aside className="hidden w-[244px] shrink-0 flex-col border-r border-white/[.07] bg-[#0e0e11] p-3 lg:flex"><div className="flex items-center gap-3 px-2 py-3"><DonnaMark/><span className="text-[15px] font-semibold tracking-tight">Donna</span><button className="ml-auto text-zinc-600 transition-colors hover:text-zinc-300"><PanelLeftClose size={17}/></button></div><nav className="mt-7 space-y-1">{items.map(({label,href,icon:Icon},i)=><motion.div initial={{opacity:0,x:-8}} animate={{opacity:1,x:0}} transition={{delay:i*.04}} key={label}>{nav(label,href,Icon)}</motion.div>)}</nav><div className="my-5 border-t border-white/[.06]"/><nav className="space-y-1">{nav("Integrations","/integrations",Puzzle)}{nav("Settings","/settings",Settings)}{nav("Privacy & permissions","/privacy",ShieldCheck)}</nav><div className="mt-auto rounded-xl border border-violet-400/[.12] bg-gradient-to-br from-violet-500/[.12] to-transparent p-3.5"><div className="mb-2 flex items-center gap-1.5 text-xs font-medium text-violet-200"><Sparkles size={13}/>Donna Pro</div><p className="text-xs leading-5 text-zinc-500">More context. More calm.</p><Link href="/settings" className="mt-3 flex w-full items-center justify-center gap-1 text-xs text-zinc-300 hover:text-white">View plans <ChevronDown size={13} className="-rotate-90"/></Link></div><div className="mt-3 flex items-center gap-2 rounded-xl p-2 hover:bg-white/[.04]"><div className="grid h-7 w-7 place-items-center rounded-full bg-gradient-to-br from-amber-200 to-rose-400 text-[10px] font-semibold text-zinc-900">NK</div><div className="min-w-0 flex-1"><p className="text-xs font-medium">Nirav K.</p><p className="text-[10px] text-zinc-600">Personal workspace</p></div><button onClick={signOut} title="Sign out" className="text-zinc-600 hover:text-zinc-200"><LogOut size={15}/></button></div></aside>; }
