import Link from "next/link";
import { CalendarDays, Clock3 } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { BriefingCard } from "@/components/briefing-card";
import { ChatWindow } from "@/components/chat-window";
import { DashboardCard } from "@/components/dashboard-cards";
import { TodoList } from "@/components/todo-list";

export default function DashboardPage() { return <AppShell><div className="mx-auto max-w-[1440px] p-5 sm:p-8"><div className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="mb-2 text-xs font-medium uppercase tracking-[.17em] text-violet-300">Tuesday, July 15</p><h1 className="text-3xl font-medium tracking-[-.04em] sm:text-[34px]">Good Morning, Nirav.</h1><p className="mt-2 text-sm text-zinc-500">Donna has prepared your daily briefing.</p></div><Link href="/calendar" className="flex items-center gap-2 self-start rounded-xl border border-white/[.09] bg-white/[.04] px-3 py-2 text-xs text-zinc-300 hover:bg-white/[.08]"><CalendarDays size={15}/>View calendar</Link></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><DashboardCard label="Open tasks" value="4" detail="2 due today" tone="violet"/><DashboardCard label="Unread messages" value="8" detail="3 need a response"/><DashboardCard label="Focus time" value="2h 30m" detail="Planned today"/><DashboardCard label="Next event" value="10:00" detail="SAT study block"/></div><div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.45fr)_minmax(330px,.75fr)]"><div className="space-y-6"><BriefingCard/><div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(220px,.78fr)]"><TodoList/><section className="rounded-2xl border border-white/[.08] bg-white/[.025] p-5"><div className="flex items-center gap-2"><Clock3 size={16} className="text-violet-300"/><p className="text-sm font-medium">Up next</p></div><div className="mt-5 border-l border-violet-400/40 pl-4"><p className="text-sm text-zinc-200">SAT study block</p><p className="mt-1 text-xs text-zinc-600">10:00 – 11:30 AM</p><p className="mt-3 text-xs leading-5 text-zinc-500">Reading comprehension · 2 assignments</p></div><Link href="/calendar" className="mt-5 inline-block text-xs text-violet-300 hover:text-violet-200">Open schedule →</Link></section></div></div><ChatWindow/></div></div></AppShell>; }
